# Generated by Django 3.2.4 on 2021-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_student_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Рабочий', 'verbose_name_plural': 'Рабочие'},
        ),
        migrations.AddField(
            model_name='branch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='branches/'),
        ),
    ]
